Fix MLflow run_id extraction

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,9 +41,16 @@ jobs:
 
       - name: Get latest MLflow run_id
         run: |
-          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
+          RUN_ID=$(ls -1t mlruns/0/ | grep -v ".trash" | head -n 1)
+
+          if [ -z "$RUN_ID" ]; then
+            echo "Error: RUN_ID tidak ditemukan!"
+            ls -R mlruns/0/ # Menampilkan isi folder untuk debug
+            exit 1
+          fi
+
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
-          echo "Model berhasil dibuat dengan Run ID: $RUN_ID"
+          echo "Model berhasil dibuat: $RUN_ID"
 
       - name: Build Docker Model Image
         run: |
